background = rgb(11111b)
base = rgb(1e1e2e)
alternate_base = rgb(313244)

text = rgb(cdd6f4)
bright_text = rgb(cdd6f4)

accent = rgb(cba6f7)
accent_secondary = rgb(b4befe)

rounding_large = 14
rounding_small = 10

font_size = 12
small_font_size = 10

font_family = CaskaydiaMono Nerd Font
font_family_monospace = CaskaydiaMono Nerd Font
