font_family CaskaydiaMono Nerd Font
font_size 13.0

background_opacity 0.92
confirm_os_window_close 0

cursor_shape block
cursor_blink_interval 0

enable_audio_bell no
window_padding_width 8

shell_integration enabled

mouse_hide_wait 2.0
scrollback_lines 10000
copy_on_select yes
mouse_map right press ungrabbed paste_from_clipboard

remember_window_size yes
placement_strategy center


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

